modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod.license}"

[[mods]]
modId = "${mod.modid}"
version = "${mod.version}"
displayName = "Spark108-Social"
authors = "Spark108"
description = "Взаимодействие с игроками и перевод игровой валюты."

[[mixins]]
config = "spark108_social.mixins.json"

[[dependencies.${mod.modid}]]
modId = "neoforge"
type = "required"
versionRange = "[${mod.neoforge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod.modid}]]
modId = "luckperms"
type = "required"
versionRange = "[5.4,)"
ordering = "AFTER"
side = "SERVER"

[[dependencies.${mod.modid}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod.modid}]]
modId = "spark108_economyapi"
type = "required"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"
